# Generated by Django 4.1.2 on 2022-12-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_profile_pic_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
